import 'reset-css';
import '../scss/styles.scss';

import renderHeader from './modules/header.js';
import removeActive from './modules/removeActive.js';
import pageNav from './modules/nav.js';

renderHeader();

const tablist = document.querySelectorAll('.header__nav-link');
const data = [
  {
    id: 27103,
    title: 'Beside the Sea #34',
    date_display: '1962',
    artist_display: 'Robert Motherwell\nAmerican, 1915-1991',
    place_of_origin: 'United States',
    credit_line: 'Barbara Neff Smith and Solomon Byron Smith Purchase Fund',
    term_titles: [
      'oil paintings (visual works)',
      'paper (fiber product)',
      'organic material',
      'drawings (visual works)',
      'prints and drawing',
    ],
    image_id: '857653de-8087-38f4-0a4c-305862f85154',
  },
  {
    id: 25838,
    title: 'Pistachio Tree at Ch\u00e2teau Noir',
    date_display: 'c. 1900',
    artist_display: 'Paul C\u00e9zanne\nFrench, 1839-1906',
    place_of_origin: 'France',
    credit_line: 'Mr. and Mrs. Martin A. Ryerson Collection',
    term_titles: [
      'watercolor',
      'Century of Progress',
      'paper (fiber product)',
      'watercolor',
      'water-base paint',
      'paint',
      'graphite',
      'drawings (visual works)',
      'prints and drawing',
      "world's fairs",
      "Chicago World's Fairs",
    ],
    image_id: 'ff4eb409-5b54-0443-8c05-270921a5de20',
  },
  {
    id: 27281,
    title: 'Madam Pompadour',
    date_display: '1915',
    artist_display: 'Amedeo Modigliani\nItalian, 1884\u20131920',
    place_of_origin: 'Italy',
    credit_line: 'Joseph Winterbotham Collection',
    term_titles: [
      'oil on canvas',
      'women',
      'painting',
      'modern and contemporary art',
      'interiors',
      'portraits',
      'fashion',
      'hats',
      'Joseph Winterbotham Collection',
    ],
    image_id: 'fdc1a755-ff86-487d-f16b-f03c40a30bee',
  },
  {
    id: 28560,
    title: 'The Bedroom',
    date_display: '1889',
    artist_display: 'Vincent van Gogh\nDutch, 1853-1890',
    place_of_origin: 'Saint-R\u00e9my-de-Provence',
    credit_line: 'Helen Birch Bartlett Memorial Collection',
    term_titles: [
      'oil on canvas',
      'oil painting',
      'Post-Impressionism',
      'interiors',
      'oil paint (paint)',
      'painting (image making)',
      'painting',
      'european painting',
      'domestic scenes',
      'Century of Progress',
      "world's fairs",
      "Chicago World's Fairs",
      'beds',
      'bedrooms',
    ],
    image_id: '25c31d8d-21a4-9ea1-1d73-6a2eca4dda7e',
  },
  {
    id: 27954,
    title: 'Terrace and Observation Deck at the Moulin de Blute-Fin, Montmartre',
    date_display: 'early 1887',
    artist_display: 'Vincent van Gogh\nDutch, 1853-1890',
    place_of_origin: 'Paris',
    credit_line: 'Helen Birch Bartlett Memorial Collection',
    term_titles: [
      'oil on canvas',
      'Post-Impressionism',
      'oil paint (paint)',
      'Century of Progress',
      'painting',
      'european painting',
      'weather/seasons',
      'leisure',
      'landscapes',
      "world's fairs",
      "Chicago World's Fairs",
    ],
    image_id: '6cb22407-be79-bf0a-1a63-fdf2b99e035b',
  },
  {
    id: 34145,
    title: 'Vincent and Tony',
    date_display: '1969',
    artist_display: 'Alex Katz\nAmerican, born 1927',
    place_of_origin: 'United States',
    credit_line: 'Gift of Society for Contemporary Art',
    term_titles: [
      'painting',
      'youth',
      'modern and contemporary art',
      'hairstyles',
      'portraits',
      'fashion',
      'boys',
    ],
    image_id: 'f1c1fd79-266b-26d8-3c14-ccb4cf3248a6',
  },
  {
    id: 45240,
    title: 'The Bathers',
    date_display: '1899-1904',
    artist_display: 'Paul Cezanne\nFrench, 1839-1906',
    place_of_origin: 'France',
    credit_line: 'Amy McCormick Memorial Collection',
    term_titles: [
      'oil on canvas',
      'Post-Impressionism',
      'oil paint (paint)',
      'Century of Progress',
      'painting',
      'european painting',
      'leisure',
      'weather/seasons',
      'women',
      'landscapes',
      "world's fairs",
      "Chicago World's Fairs",
    ],
    image_id: '2e166f7c-a959-d686-eeb0-a63a52a4d368',
  },
  {
    id: 41236,
    title: 'Dobeckmun Metallic Stripe (Curtain Fabric)',
    date_display: '1948',
    artist_display: 'Designed by Dorothy Liebes (American, 1897\u20131972)\nUnited States',
    place_of_origin: 'United States',
    credit_line: 'Gift of Dorothy Liebes Design, Inc.',
    term_titles: [
      'weaving',
      'wool (textile)',
      'Modernism',
      'twill weaving',
      'stripes',
      'textile',
      'cellulose acetate film',
      'cotton (fiber)',
      'foil',
      'metal',
      'rayon',
      'silk (fiber)',
      'weaving',
      '20th Century',
    ],
    image_id: '4c79f7b4-74fa-19a5-e57f-48a5e192ee5d',
  },
  {
    id: 61878,
    title: 'Still Life',
    date_display: '1914',
    artist_display: 'Georges Braque\nFrench, 1882-1963',
    place_of_origin: 'France',
    credit_line: 'Given in memory of Charles Barnett Goodspeed by Mrs. Charles B. Goodspeed',
    term_titles: [
      'collage',
      'collage (technique)',
      'paper (fiber product)',
      'watercolor',
      'water-base paint',
      'paint',
      'organic material',
      'graphite',
      'charcoal',
      'drawings (visual works)',
      'prints and drawing',
    ],
    image_id: 'ad9f6106-ea49-8b84-ec55-5862f6dce6c6',
  },
  {
    id: 62371,
    title: 'Madame Cezanne in a Yellow Chair',
    date_display: '1888-90',
    artist_display: 'Paul Cezanne\nFrench, 1839-1906',
    place_of_origin: 'France',
    credit_line: 'Wilson L. Mead Fund',
    term_titles: [
      'oil on canvas',
      'Post-Impressionism',
      'portraits',
      'oil paint (paint)',
      'painting',
      'european painting',
      'emotions',
      'women',
      'families',
    ],
    image_id: '4822cd01-44ac-041a-36b8-c0542377b750',
  },
];

pageNav(tablist, removeActive);
